import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./(component)/AuthProvider";
import Nav from "./(component)/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <Nav />
          <div className="m-3">{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
